#!/usr/bin/env bash
docker stop compose
docker rm compose
docker run -itd --net=host -v `pwd`/../user-data:/user-data -v `pwd`/public_html:/var/www/html/public_html --name compose afdaniele/compose:devel-amd64
