#!/usr/bin/env bash
docker stop blog
docker rm blog
docker run \
    -itd \
    --net=host \
    -v `pwd`/../user-data-erika:/user-data \
    -v `pwd`/public_html:/var/www/html/public_html \
    -e HTTP_PORT=8082 \
    --name blog \
    afdaniele/compose:debug-amd64
