#!/bin/bash
# recordCam.sh
# ------------
# Every day at 1AM, this script goes through the videos, grabs a frame every X seconds, performs a diff between
# two consecutive frames, and stores the difference (float value) into a CSV file.
# -----------
# Author: Andrea F. Daniele
# License: BSD

# check whether the time is within the interval of interest 1AM->7AM.
timestamp="`date +%T`"
if [[ "$timestamp" < "00:59:00" || "$timestamp" > "06:59:00" ]]; then
    exit 0
fi

# Get yesterday's date.
yesterday="`date -d 'yesterday 13:00' '+%Y-%m-%d'`"

# Where the Web-format video files will be saved.
SCRIPTdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASEpath=`cat $SCRIPTdir/../../config/configuration.json | grep "camera_1_raw_data_path" | sed 's/[,:"]//g' | awk '{print $2}'`
WEBMpath=`cat $SCRIPTdir/../../config/configuration.json | grep "camera_1_webm_data_path" | sed 's/[,:"]//g' | awk '{print $2}'`
INPUTpath=$BASEpath'/'$yesterday
OUTPUTpath=$WEBMpath'/'$yesterday

# Exit if nothing was recorded yesterday
if [[ ! -d "$INPUTpath" ]]; then
  exit 0
fi

# Create the destination folder if it does not exist.
if [[ ! -d "$OUTPUTpath" ]]; then
  mkdir -p "$OUTPUTpath"
fi

# Get the list of .MP4 files
FILES=`ls -l $INPUTpath | grep .mp4 | awk '{print $9}'`

# Use ffmpeg to convert the FullHD videos into Low-Resolution Low-Bitrate video files
for IN in $FILES; do
  OUT="$OUTPUTpath/web_$IN"
  ffmpeg -i "$INPUTpath/$IN" -movflags faststart -an -strict experimental -vcodec libx264 -f mp4 -crf 22 -s 640x360 $OUT
done

# Where the motion detection logs will be saved.
DESTpath=`cat $SCRIPTdir/../../config/configuration.json | grep "camera_1_activity_data_path" | sed 's/[,:"]//g' | awk '{print $2}'`
ACTIVITYpath=$DESTpath'/'$yesterday
MASKfile=$SCRIPTdir'/../../config/motion_detection_cam1_mask.jpg'

# Create the destination folder if it does not exist.
if [[ ! -d "$ACTIVITYpath" ]]; then
  mkdir -p "$ACTIVITYpath"
fi

# Use OpenCV to perform motion detection on the Low-Resolution videos
echo 'Running motion detection on '$yesterday'...'
MOTION_DETECTION_MODULE=$SCRIPTdir'/../src/motion_detection/motion_detection.py'
python "$MOTION_DETECTION_MODULE" "$OUTPUTpath" "$ACTIVITYpath" "$MASKfile"
